-keep class io.github.supermonster003.autojs6.plugin.htmlpreviewer.** { *; }
-keep class org.autojs.plugin.common.api.PluginInfo { *; }
-keep class org.autojs.plugin.explorer.api.** { *; }
-dontwarn kotlinx.parcelize.Parcelize
